### ISSUE TITLE
Trying to access nonce, balance, storageRoot and codeHash via the state trie

### ISSUE THREAD

**Issue by JEJodesty** [tpmccallum/ethereum_database_research_and_testing#3]
Hi @tpmccallum,
I attempting to access nonce, balance, storageRoot and codeHash via the state trie given your example in the 1st comment without success. I'm using a data directory within my geth node, an existing stateRoot in the Ethereum Blockchain
```
db = levelup(leveldown('/root/.ethereum/geth/chaindata'));
var root = '0xc23aebee71a1e6f988773af2eba7b55a57f659b565c392edaf99b5f765d30574';
```
It produces a black output despite me accessing a stateRoot within the correct block height indicating that the stateRoot exist.

Your help would be greatly appreciated!

Thank You,
Joshua

```
var Trie = require('merkle-patricia-tree/secure');
var levelup = require('levelup');
var leveldown = require('leveldown');
var RLP = require('rlp');
var assert = require('assert');

//Connecting to the leveldb database
// var db = levelup(leveldown('/home/timothymccallum/gethDataDir/geth/chaindata'));
db = levelup(leveldown('/root/.ethereum/geth/chaindata'));

//Obtaining the state root (of the latest block) using this command web3.eth.getBlock(web3.eth.defaultBlock).stateRoot
// var root = '0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544';
var root = '0xc23aebee71a1e6f988773af2eba7b55a57f659b565c392edaf99b5f765d30574';

//Creating a trie object of the merkle-patricia-tree library
var trie = new Trie(db, root);

//Creating a nodejs stream object so that we can access the data
var stream = trie.createReadStream()

//Turning on the stream (because the node js stream is set to pause by default)
stream.on('data', function (data){
  //Capture the RLP serialised data structure
  var arrayOfStateValues = RLP.decode(data.value);
  //Loop through the data of the 3 accounts in the array to obtain the nonce, balance, storageRoot and codeHash for each one 
  for (i = 0; i < arrayOfStateValues.length; i++){ 
    console.log(RLP.decode(arrayOfStateValues[i], [skipRemainderCheck=false])); 
    console.log("");
  }
  
});
```

**Comment by tpmccallum** [comment]
Hi @JEJodesty 
It has been a few weeks since I have played with this. 
Please look at the following  and compare and contrast the differences between what you are trying and what I have provided in my installation and code examples.
**Installing npm, node, level and ethereumjs**
https://gist.githubusercontent.com/tpmccallum/0e58fc4ba9061a2e634b7a877e60143a/raw/ec53049533d08f8db226f0fbe3510191bb94de55/epn_18.md
**Print a list of the Etherem account keys**
https://gist.githubusercontent.com/tpmccallum/2dfa62c820d87e0105ee14bfe77b59ce/raw/bb14bea5a22f8d7d39a12bc3cc3e5f2a850a8022/epn_19.md
**Example of getting the account balance**
https://gist.githubusercontent.com/tpmccallum/bd9e5538346e1defb1234f37cfd33eda/raw/43456edfcc46f603539de610876c9d843de20990/get_account_balance.md

Hope this helps.

I wrote up a whole article on this 
https://medium.com/cybermiles/diving-into-ethereums-world-state-c893102030ed
Feel free to check it out, the code comes in at the end (after we talk about Ethereum state etc etc.)

Kind regards
Tim

**Comment by JEJodesty** [comment]
Hi TIm,
Ive tried every one of your examples in the previous comment and read your article over the past few days (I'm a bit of a fan!). the only modification i made to the codebase was either replacing your stateRoot with and existing one in the Ethereum blockchain (["Print a list of the Etherem account keys"](https://gist.githubusercontent.com/tpmccallum/2dfa62c820d87e0105ee14bfe77b59ce/raw/bb14bea5a22f8d7d39a12bc3cc3e5f2a850a8022/epn_19.md)), and  providing a stateRoot and address from a transaction within a block whose block head has the same state root (["Example of getting the account balance"](https://gist.githubusercontent.com/tpmccallum/bd9e5538346e1defb1234f37cfd33eda/raw/43456edfcc46f603539de610876c9d843de20990/get_account_balance.md))

I would greatly appreciate your help :)

With Appreciation,
Josh

**Comment by JEJodesty** [comment]
Hi @tpmccallum ,
Solved it! Issue: Corrupted leveldb database.

Thanks for your help!
-Josh

**Comment by tpmccallum** [comment]
Can you paste what you did in the end?
Even a link to a Gist would be great.
Well done!
